Jobs endpoints
daminals/orcanet-rust pull request #6
Opened 2024-04-25 18:25 UTC by andrewctam

2024-04-25 18:30 UTC, andrewctam commented
@daminals @ingrettable Can you check if these changes are ok before I continue with the other endpoints?

2024-04-27 01:46 UTC, andrewctam commented
@daminals @ingrettable I think this PR is in a good state for review, before the changes become too large. We also have some changes in the "jobs-endpoints-market" branch for peer related routes, but those can be reviewed later once the Sea Horse market is complete.

2024-04-27 15:24 UTC, xiej2520 commented
Note: the `get_jobs_state` method returns a clone of the jobs state, some of the route handlers that modify it do not seem to take that account, the changes they make will not show up.

2024-04-28 04:11 UTC, xiej2520 commented
I branched from this onto https://github.com/daminals/orcanet-rust/tree/market_peer_merge_route,
with SeaHorses' market implementation (currently waiting on full implementation).
I restructured the endpoints to be by team and am periodically merging Sea Horses' commits onto the branch, so hopefully we can get a fully working market + peer + server this week.

2024-04-29 14:01 UTC, daminals commented
Instead of having the jobs/files endpoints located within the producer module, it would probably make sense to make a separate server model, since the local producer is not going to be handling the jobs nor downloading files on behalf of the client, that would either be consumer (but it shouldn't go into consumer because splitting endpoints into multiple modules is a maintenance disaster) or server functionality

2024-04-29 14:36 UTC, andrewctam commented
I moved files.rs and jobs.rs to /transfer. There is already a server.rs so I don't think I could have called it server.

2024-04-29 21:44 UTC, daminals requested changes

2024-04-29 21:44 UTC, daminals commented on peernode/src/peer-node/routes/file_routes.rs
> +// }
```suggestion
```

Remove unused comments

2024-04-29 21:44 UTC, daminals commented on peernode/src/peer-node/routes/file_routes.rs
> +    let producer = "this arg was removed"; //query.producer.clone()";
```suggestion
    let producer = "this arg was removed";
```

2024-04-29 21:46 UTC, daminals commented
Have you been able to test these endpoints with the actual desktop client?

2024-04-29 21:49 UTC, andrewctam commented
I believe @xiej2520 tried, Jacky did you have success with it?

2024-04-29 21:50 UTC, xiej2520 commented
I tried with orcanet-desktop but I don't think it has all the endpoints implemented, it has `get-peers` but we haven't done that yet (waiting on market).

2024-04-29 21:52 UTC, daminals approved these changes

2024-04-29 22:04 UTC, merged